name: 🐛 Something isn't working
description: Let us know if something in the app isn't working right
title: ""
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for letting us know about this issue! We'll look into it as soon as possible.

  - type: textarea
    id: problem
    attributes:
      label: What's the problem?
      description: Tell us what happened
      placeholder: "I was trying to... but then..."
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What did you expect to happen instead?
      placeholder: "I expected..."
    validations:
      required: true

  - type: input
    id: device-info
    attributes:
      label: What iPhone or iPad are you using?
      placeholder: "iPhone 14, iPad Air, etc."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: If you can, add a screenshot to show us the problem
      placeholder: You can drag and drop images here

  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Is there anything else you'd like us to know?
      placeholder: "This also happens when..."