name: ✨ I have an idea
description: Share your idea for improving the app
title: "[Idea]: "
labels: ["feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! We love hearing from our users.

  - type: textarea
    id: idea
    attributes:
      label: What's your idea?
      description: Tell us about your idea for the app
      placeholder: "It would be great if the app could..."
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why would this be helpful?
      description: How would this make the app better for you?
      placeholder: "This would help me because..."
    validations:
      required: true

  - type: dropdown
    id: importance
    attributes:
      label: How important is this to you?
      options:
        - Very important - I really need this
        - Pretty important - This would help a lot
        - Nice to have - Would be cool but not essential
        - Just an idea - Take it or leave it
    validations:
      required: true

  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Any other details about your idea?
      placeholder: "I've seen something similar in..."